### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by lrq3000** [barrettfdavis/online_actogram#1]
Dear Barrett,

Thank you very much for this wonderful idea and software, i already praised it on reddit but it's certainly worth i do it again here ;-)

Could you please clarify the license of your software to ease reuse and/or fork/PR developments?

Thank you very much in advance!
Best regards,
Stephen

**Comment by barrettfdavis** [comment]
Hi Stephen,

Merci bien, you're too kind! Thank you for your question as well. I've just added an MIT license to the project, so feel free to use, copy, modify, merge, etc. 

Best, 
Barrett

**Comment by lrq3000** [comment]
Thank you so much Barrett!

Sorry for the delay in my response, lots of things going on, but great progress on lots of sides! I'm going to start the GitHub organization soon to regroup opensource softwares and tools developed to help with managing non-24, would you like your project to be included in the organization (and you'll of course have admin access to your repo there)? :-)

In the upcoming months I'll contribute to your project to add support for more browsers and to add automatic pre-diagnosis of circadian rhythm disorders from actograms! I determined that browser plugins will not only be timeconsuming to develop, but also limited to one browser, whereas your approach is more generalizable and cross-platform. I'll just make binaries using pyInstallers for Windows users to easily use it (and hopefully MacOSX later down the line :-)).
